Add capturing and persisting screenshots periodically
OutOfAxis/fugo-player-bs pull request #3
Opened 2022-11-04 13:54 UTC by ilyai

Related PR: https://github.com/OutOfAxis/fugo-player/pull/392

2022-11-07 12:01 UTC, mrsln requested changes

2022-11-07 12:01 UTC, mrsln commented on autorun.brs
> +        quality: 75
```suggestion
        quality: 95
```

Quality can be better since PlayerJS [does compression](https://github.com/OutOfAxis/fugo-player/blob/feature/brightsign-screenshot-support/src/stateMachines/ScreenshotMachine.ts#L238) already 

<img width="839" alt="Screenshot 2022-11-07 at 16 57 37" src="https://user-images.githubusercontent.com/96596/200304633-2cd1bbca-247e-4f8b-be0f-2b3924e3175b.png">

2022-11-07 12:01 UTC, mrsln commented on autorun.brs
> +        height: 405
1. Why is the height a weird number? Did you want to have 720p (it's 1280x720)? 
2. PlayerJS already resizes the screenshot so this could be FullHD or, ideally, match the screen resolution.

2022-11-08 12:21 UTC, ilyai commented on autorun.brs
> +        height: 405
1. We have such resolution for screenshots from Samsung for example: https://screenshots.fugo.ai/f7200214-cef3-4d20-b130-f43ac37e3158/4ac9e288-11ec-4f76-b5ef-b2cbcdc7305c/screenshot.jpg
2. Doesn't seem that PlayerJS is resizing: https://github.com/OutOfAxis/fugo-player/blob/dev/src/stateMachines/ScreenshotMachine.ts#L190 , also in CMS we're displaying screenshots in a box of 12rem height, do you think it's going to be any difference for higher resolutions?

2022-11-08 15:05 UTC, mrsln commented on autorun.brs
> +        height: 405
ok, I guess we can change this later if we have the auto-updating feature

2022-11-08 15:05 UTC, mrsln approved these changes

2022-11-08 15:34 UTC, merged